# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-rootreasury

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Personal finance manager for SailfishOS
Version:    1.5
Release:    1
Group:      Qt/Qt
License:    GPL-3.0-or-later
URL:        https://github.com/RootGPT-YouTube
Source0:    %{name}-%{version}.tar.bz2
Source100:  RooTreasury.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Provides:   RooTreasury = %{version}-%{release}
Obsoletes:  RooTreasury < %{version}-%{release}
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
RooTreasury is a personal finance manager for SailfishOS.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/RooTreasury
%{_datadir}/RooTreasury
%{_datadir}/applications/RooTreasury.desktop
%{_datadir}/icons/hicolor/86x86/apps/RooTreasury.png
%{_datadir}/icons/hicolor/108x108/apps/RooTreasury.png
%{_datadir}/icons/hicolor/128x128/apps/RooTreasury.png
%{_datadir}/icons/hicolor/172x172/apps/RooTreasury.png
%{_datadir}/icons/hicolor/256x256/apps/RooTreasury.png
# >> files
# << files
